packages = {
    "# --- Core Social Media API Interaction ---": [
        "praw==7.8.1",  # The Python Reddit API Wrapper for data sourcing
        "atproto==0.0.61",  # For interacting with Bluesky's AT Protocol
    ],
    "# --- LLM API Clients ---": [
        "openai==1.35.13",          # For interacting with OpenAI models (GPT-4, etc.)
        "google-generativeai==0.7.2", # For interacting with Google models (Gemini)
        "anthropic==0.29.0"         # For interacting with Anthropic models (Claude)
    ],
    "# --- Data Cleaning and Handling ---": [
        "beautifulsoup4==4.12.3", # For parsing HTML and cleaning text
        "pandas==2.2.2",          # For data manipulation and analysis
        "numpy==1.26.4"            # For numerical operations, often a dependency for ML libraries
    ],
    "# --- Machine Learning & NLP (for Evaluation & Analysis) ---": [
        "scikit-learn==1.5.1",    # For classical ML algorithms, metrics, and evaluation tools
        "torch==2.4.0",           # Core deep learning framework (PyTorch)
        "transformers==4.42.4",   # Provides access to pre-trained models for evaluation (from Hugging Face)
        "textstat==0.7.8",        # For text statistics and analysis
        "nltk==3.9.1",            # Natural Language Toolkit for text processing
    ],
    "# --- Utilities ---": [
        "python-dotenv==1.0.1"    # For managing API keys and environment variables securely
    ]
}

try:
    with open("requirements.txt", "w") as f:
        f.write("# This file was generated by generate_requirements.py\n")
        f.write("# Use 'pip install -r requirements.txt' to install all dependencies.\n\n")
        
        for comment, libs in packages.items():
            f.write(f"{comment}\n")
            for lib in libs:
                f.write(f"{lib}\n")
            f.write("\n") # Add a blank line for readability
            
    print("Successfully created 'requirements.txt' file.")
    print("Next step: Run 'pip install -r requirements.txt' in your virtual environment.")

except IOError as e:
    print(f"Error: Could not write to file 'requirements.txt'.")
    print(f"Details: {e}")