[phases.setup]
nixPkgs = ['python311', 'pip']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['python -c "import nltk; nltk.download(\'vader_lexicon\'); nltk.download(\'punkt\')"']

[start]
cmd = 'python app.py'
