"""
Requirements file generator for the Social Media Language Analysis Project.

This script creates a requirements.txt file with all necessary dependencies
for the project. It categorizes the packages into sections for better
organization and readability, ensures proper formatting for pip, and includes
comments to explain the purpose of each section.
"""

packages = {
    "# --- Core Social Media API Interaction ---": [
        "praw==7.8.1",       # Latest stable Python Reddit API Wrapper
        "atproto==0.0.62",   # AT Protocol SDK (latest as of Aug 17, 2025)
    ],
    "# --- LLM API Clients ---": [
        "openai==1.107.0",           # OpenAI Python SDK (latest as of Sep 8, 2025)
        "google-generativeai==0.8.5",
        "anthropic==0.59.0"
    ],
    "# --- Data Cleaning and Handling ---": [
        "beautifulsoup4==4.13.4",
        "pandas==2.3.1",
        "numpy==2.3.3",
        "seaborn==0.13.2"
    ],
    "# --- Machine Learning & NLP (for Evaluation & Analysis) ---": [
        "scikit-learn==1.7.1",
        "torch==2.4.0",
        "textstat==0.7.8",
        "nltk==3.9.1",
        "conc==0.1.2",
        "xgboost==3.0.0",
        "lightgbm==4.6.0",
        "catboost==1.2.8",
        "tqdm==4.65.0"
    ],
    "# --- Utilities ---": [
        "python-dotenv==1.1.1",
        "pytest==8.4.0",
    ]
}

def generate_requirements():
    try:
        with open("requirements.txt", "w") as f:
            f.write("# This file was generated by generate_requirements.py\n")
            f.write("# Use 'pip install -r requirements.txt' to install all dependencies.\n\n")

            for comment, libs in packages.items():
                f.write(f"{comment}\n")
                for lib in libs:
                    f.write(f"{lib}\n")
                f.write("\n")

        print("Successfully created 'requirements.txt' file.")
        print("Next step: Run 'pip install -r requirements.txt' in your virtual environment.")

    except IOError as e:
        print(f"Error: Could not write to file 'requirements.txt'.")
        print(f"Details: {e}")

if __name__ == "__main__":
    generate_requirements()
